-- Create schema if not exists LINK;
-- Create schema if not exists AUTHENTICATED_USER;
-- Create schema if not exists ANONYMOUS;

create TABLE IF NOT EXISTS AUTHORITIES (
    ID IDENTITY PRIMARY KEY,
    USERNAME VARCHAR(45) NOT NULL,
    AUTHORITY VARCHAR(45) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS users (
   username VARCHAR(50) NOT NULL PRIMARY KEY,
   password VARCHAR(100) NOT NULL,
   enabled BOOLEAN NOT NULL
);
-- --
-- create table authenticated_user.link (is_latest boolean not null, marked_for_deletion boolean not null, created_at timestamp(6), id bigint generated by default as identity, updated_at timestamp(6), valid_from timestamp(6), valid_until timestamp(6), short_link_id uuid, description varchar(255), original_url varchar(255), primary key (id));
--
--
-- create table authenticated_user.link_user (id bigint generated by default as identity, link_id uuid, user_name varchar(255), primary key (id));